### PR TITLE
[WIP, ENH] Moving to github actions for CI

### PR DESCRIPTION
**Pull request by sjsrey**

### CODE REVIEW

**Comment by jGaboardi** [comment]
* should we include a `requirements_plus.txt` with `numba`?
* is `geopandas` only used for testing?

**Comment by sjsrey** [comment]
[This passes](https://github.com/sjsrey/esda/runs/839451527?check_suite_focus=true) for me. Maybe we need a branch to work on the transition for the test migration from travis to gha?

**Comment by jGaboardi** [comment]
Seems to have just been triggered.

**Comment by sjsrey** [comment]
> Seems to have just been triggered.

Yah, I pushed a new branch: https://github.com/pysal/esda/tree/gha

**Comment by sjsrey** [comment]
>     * should we include a `requirements_plus.txt` with `numba`?
> 
>     * is `geopandas` only used for testing?

yes on geopandas for testing.

not sure on requirements_plus.txt over just having the different ci/*.yml files?

**Comment by jGaboardi** [comment]
> > ```
> > * should we include a `requirements_plus.txt` with `numba`?
> > 
> > * is `geopandas` only used for testing?
> > ```
> 
> 
> yes on geopandas for testing.
> 
> 
> not sure on requirements_plus.txt over just having the different ci/*.yml files?

Shouldn't we have both? The `requirements_plus.txt` should be included in `MANIFEST.in` and the `./ci/*` files are simply for testing.

**Comment by jGaboardi** [comment]
`requirements_plus.txt` should be added to `setup_package()` within `setup.py`.

**Comment by jGaboardi** [comment]
Let's go ahead and merge this, then I'll add a [`dependabot.yml`](https://github.com/pysal/libpysal/blob/master/.github/dependabot.yml) in the next PR?

**Pull request merged**
