### PR TITLE
ENH - Join count tails

### PR DESCRIPTION
**Pull request by rose-pearson**
In response to https://github.com/pysal/esda/issues/48.

1. Added autocorr_neg and autocorr_pos as instance attributes to Join_Counts class
2. Added relevant tests to the Join_Counts_Tester class

Will create a separate branch on my fork / fork off my fork to update the docs associated with Join_Counts

### CODE REVIEW

**Comment by ljwolf** [comment]
Will the `autocorr_bw` get a chi-square test as well?

**Comment by rose-pearson** [comment]
Hi @ljwolf we are a little unsure about the statistical meaningfulness of this - as this will produce a 2x1 table upon which to perform our chi2 test. Any thoughts?

**Comment by ljwolf** [comment]
I think the correct positive autocorrelation test is on `bb+ww`. Currently, the chisquare test on `bw` joins gives you a significance of negative vs. null dependence.  a test of `bb+ww` would give a result on positive vs. null dependence. I think that makes sense. Treat `bb+ww` as if it were `bw`.

**Comment by sjsrey** [comment]
> I think the correct positive autocorrelation test is on `bb+ww`. Currently, the chisquare test on `bw` joins gives you a significance of negative vs. null dependence. a test of `bb+ww` would give a result on positive vs. null dependence. I think that makes sense. Treat `bb+ww` as if it were `bw` in a one tail test.

So we could add a pseudo p-value on the bb+ww and return that?

The chi-2 was on the 2x2 table [[BB, BW], [WB, WW]], and we would have 0 degrees of freedom with a 2x1 table, so the pseudo p on the BB+WW makes the most sense to me.

**Comment by rose-pearson** [comment]
Thanks @ljwolf and @sjsrey, and added pseudo p of the autocorr values.

**Comment by ljwolf** [comment]
I'm thinking about the goodness of fit chi squared statistic for the observed [(bb+ww), bw] versus each of the simulations? Then, the test is how many chi-squared statistics are larger than the observed comparison to the pooled null, where we take [(bb+ww),  bw] of *all* simulations.

**Comment by sjsrey** [comment]
> I'm thinking about the goodness of fit chi squared statistic for the observed [(bb+ww), bw] versus each of the simulations? Then, the test is how many chi-squared statistics are larger than the observed comparison to the pooled null, where we take [(bb+ww), bw] of _all_ simulations.

Something like:

stat = (Pos_o - E[Pos])^2  +  (Neg_o - E[Neg])^2

where Pos_o is observed (BB+WW), and E[Pos] = (1/r) \sum_r (BB+WW)_r

and the stat~chi_2(1 dof).

is this along the lines of what you had in mind?

**Comment by sjsrey** [comment]
> > I'm thinking about the goodness of fit chi squared statistic for the observed [(bb+ww), bw] versus each of the simulations? Then, the test is how many chi-squared statistics are larger than the observed comparison to the pooled null, where we take [(bb+ww), bw] of _all_ simulations.
> 
> Something like:
> 
> stat = (Pos_o - E[Pos])^2 + (Neg_o - E[Neg])^2
> 
> where Pos_o is observed (BB+WW), and E[Pos] = (1/r) \sum_r (BB+WW)_r
> 
> and the stat~chi_2(1 dof).
> 
> is this along the lines of what you had in mind?

r=number of permutations

**Comment by rose-pearson** [comment]
Cool. I've added some tests. TBH the stats is going a bit over my head. I think it would make the most sense to have a chat tomorrow @ljwolf. I'll bring my mic in tomorrow - so perhaps we can call.

**Comment by sjsrey** [comment]
Merging what @rose-pearson has done at scipy. I will add other dimensions we discussed in a different pr shortly.

**Pull request merged**
