### PR TITLE
permutation inference performance using numba

### PR DESCRIPTION
**Pull request by ljwolf**
This is a stub to work on performance in the permutational inference engine using numba.

### CODE REVIEW

**Comment by ljwolf** [comment]
At this phase, we've got an 8x speedup over the current implementation. From here, we have three tasks. 

Conceptually, we want the final implementation to look like this:

```python
def crand_plus(*data, local_function=moran_i):
    cardinalities, weight_pointers, *etc = setup_crand()
    with multiprocessing.Pool() as P:
        larger, random_locals = P.map(_do_one_observation, stuff_needed_for_that_iteration)
    return larger, random_locals
```

## defining the inner loop & lifting it into a numba method. 

We need to lift up the body of `neighbors_perm_plus` (e.g. [l1655](https://github.com/ljwolf/esda/blob/moran-perf/esda/moran.py#L1655)) into its own thing. This will entail solving a few issues:
- [ ] indexing into the flat weights array? *is the start position for i given by `numpy.cumsum(cardinalities)[i]`? 
- [ ] defining the signature of `_do_one_observation`. It'll probably need 
    - its weights or a pointer & into the weights flat array
    - the cardinality of i
    - the permutation matrix
    - data for z
    - the index of the observation

## parallelizing the computation
If (and only if) there's gains to be made by parallelizing the simulations, we want to explore using [`joblib`](https://joblib.readthedocs.io/en/latest/parallel.html), which should be available on all platforms. 

## defining local functions
Ideally, we'd like to implement the permutation logic *once* and then use it in all permutation-inference driven things. If we do that, we need to define something like a numba-fied local statistic for anything using the permutation inference engine. For example, a Moran version might be:

```python
@njit(fastmath=True)
def local_statistic(i, z, permutations, cardinality, weights_i):
    mask = numpy.ones_like(z)
    n = z.shape[0]
    scaling = (n - 1) / (z * z).sum()
    mask[i] = False
    z_no_i = z[mask].reshape(z.shape)
    flat_random_z = z_no_i[permutations[:, :cardinality]]
    z_no_i_lag = flat_random_z.reshape(-1,cardinality) @ weights_i
    rlisa = z[i] * z_no_i_lag.sum(axis=1) * scaling
    return rlisa
```


This will enable us to pass arbitrary JIT-ted functions to the random permutation engine.

**Comment by sjsrey** [comment]
> ## defining the inner loop & lifting it into a numba method.
> 
> We need to lift up the body of `neighbors_perm_plus` (e.g. [l1655](https://github.com/ljwolf/esda/blob/moran-perf/esda/moran.py#L1655)) into its own thing. This will entail solving a few issues:

lifting is pending at https://github.com/ljwolf/esda/pull/4

**Comment by ljwolf** [comment]
Now, we have a working conditional permutation inference engine in `crand.py`, as well as local statistics functions that can be computed on these conditioanl permutation index matrices. What is now needed is to hook up each class to the engine and validate the results. 

- [ ] Moran_Local
- [ ] Moran_Rate_Local (should connect identical to Moran_Local)
- [ ] Moran_Local_BV (called `local_wartenburg` in `crand.py`) 
- [ ] Geary_Local (does not currently exist)
- [ ] Gamma_Local (does not currently exist)
- [ ] G_Local (needs to be implemented in `crand.py`
- [ ] Spatial_Pearson_Local (in lee.py)
- [ ] Local Tau?

**Comment by ljwolf** [comment]
OK, worked on this locally until a point where I discovered the following issue. 

In `compute_chunk(...)`, `i` will now be an index *within the chunk*. This means that, when we call on a [local statistical function](https://github.com/pysal/esda/pull/116/files#diff-1fd239570b4623d6ce23f0e268495633R138) like `local_moran(i,z, permuted_ids, weights_i, scaling)`, **`i` is not the absolute index, it is the chunk-index.**

In order for the local statistics to work, we need to be able to recover the **global**, not **chunk** index of the observation. I think that's done by chunk_start+i right?

**Comment by ljwolf** [comment]
Using `chunk_start + i` gives us valid p-values.

**Comment by darribas** [comment]
I confirm `Moran_Local` works and retains competitive timings both single and multi-thread.

**Comment by darribas** [comment]
I've started a notebook to streamline comparisons [here](https://github.com/darribas/esda/blob/moran-perf/perf-comparison.ipynb). Not finished yet but should allow us to test timings on counties, tracts and blocks. Easy to extend.

**Comment by ljwolf** [comment]
Great! I think since the perf is stable after generalizing the local stats function, we can both work on profiling it better and building out the links to all the local stats. 

Very exciting! We're nearly done 😁

**Comment by ljwolf** [comment]
# Remaining to do

- [ ] hook up to the *existing* estimator classes
 - [ ] Moran Bivariate
 - [ ] Moran Rate
- [ ] Implement getis-ord local stat in `crand.py`
- [ ] write tests to check that stuff passes down to numba correctly
- [ ] set numba as default
- [ ] merge

**Comment by sjsrey** [comment]
> # Remaining to do
> 
>     * [ ]  hook up to the _existing_ estimator classes
>       
>       * [ ]  Moran Bivariate
>       * [ ]  Moran Rate
> 
>     * [ ]  docstrings in `crand.py`
> 
>     * [ ]  Implement getis-ord local stat in `crand.py`
> 
>     * [ ]  write tests to check that stuff passes down to numba correctly
> 
>     * [ ]  set numba as default
> 
>     * [ ]  merge

Getting back into the loop here to help with the remaining steps. I'm hitting the following:
image

from cell 6 of `moran-perf.ipynb`. Any ideas?

**Comment by ljwolf** [comment]
Hmm...


Could you take a pic of the whole traceback? Usually thats an issue with jnout types

**Comment by sjsrey** [comment]
> Hmm...
> 
> Could you take a pic of the whole traceback? Usually thats an issue with jnout types

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-6-6abfeca37265> in <module>
      1 reload(esda.moran)
----> 2 lisa = esda.Moran_Local(db[y_name], w, permutations=PERMS, numba=True)
      3 get_ipython().run_line_magic('timeit', 'lisa = esda.Moran_Local(db[y_name], w, permutations=PERMS, numba=True)')

~/Dropbox/p/pysal/src/subpackages/esda/esda/moran.py in __init__(self, y, w, transformation, permutations, geoda_quads, numba, n_jobs, keep_simulations)
    991                     keep_simulations,
    992                     n_jobs=n_jobs,
--> 993                     stat_func=_local_moran,
    994                 )
    995                 self.sim = np.transpose(self.rlisas)

~/Dropbox/p/pysal/src/subpackages/esda/esda/crand.py in crand(z, w, observed, permutations, keep, n_jobs, stat_func)
     60             scaling,  # scaling applied to all statistics
     61             keep,  # whether or not to keep the local statistics
---> 62             stat_func,
     63         )
     64     else:

~/anaconda3/envs/analytical/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    399                 e.patch_message(msg)
    400 
--> 401             error_rewrite(e, 'typing')
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info

~/anaconda3/envs/analytical/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345 
    346         argtypes = []

~/anaconda3/envs/analytical/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    666             value = tp()
    667         if value.__traceback__ is not tb:
--> 668             raise value.with_traceback(tb)
    669         raise value
    670 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (array(float64, 2d, C), array(bool, 2d, C))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
In definition 12:
    TypeError: unsupported array index type array(bool, 2d, C) in [array(bool, 2d, C)]
    raised from /home/serge/anaconda3/envs/analytical/lib/python3.7/site-packages/numba/typing/arraydecl.py:71
In definition 13:
    TypeError: unsupported array index type array(bool, 2d, C) in [array(bool, 2d, C)]
    raised from /home/serge/anaconda3/envs/analytical/lib/python3.7/site-packages/numba/typing/arraydecl.py:71
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at /home/serge/Dropbox/p/pysal/src/subpackages/esda/esda/crand.py (263)

File "esda/crand.py", line 263:
def _prepare_univariate(i, z, permuted_ids, weights_i):
    <source elided>
    mask[i] = False
    z_no_i = z[mask]
    ^

[1] During: resolving callee type: type(CPUDispatcher(<function _prepare_univariate at 0x7f5a4fd71c20>))
[2] During: typing of call at /home/serge/Dropbox/p/pysal/src/subpackages/esda/esda/crand.py (292)

[3] During: resolving callee type: type(CPUDispatcher(<function _prepare_univariate at 0x7f5a4fd71c20>))
[4] During: typing of call at /home/serge/Dropbox/p/pysal/src/subpackages/esda/esda/crand.py (292)


File "esda/crand.py", line 292:
def local_moran(i, z, permuted_ids, weights_i, scaling):
    zi, zrand = _prepare_univariate(i, z, permuted_ids, weights_i)
    ^

[1] During: resolving callee type: type(CPUDispatcher(<function local_moran at 0x7f5a4fd77290>))
[2] During: typing of call at /home/serge/Dropbox/p/pysal/src/subpackages/esda/esda/crand.py (151)

[3] During: resolving callee type: type(CPUDispatcher(<function local_moran at 0x7f5a4fd77290>))
[4] During: typing of call at /home/serge/Dropbox/p/pysal/src/subpackages/esda/esda/crand.py (151)


File "esda/crand.py", line 151:
def compute_chunk(
    <source elided>
        # ------
        rstats = stat_func(chunk_start + i, z, permuted_ids, weights_i, scaling)
        ^
```

**Comment by ljwolf** [comment]
Odd. This suggests that the mask matrix is a 2-dimensional array. When the mask is created, create it as a flat array?

**Comment by sjsrey** [comment]
Is this the relevant [mask](https://github.com/ljwolf/esda/blob/moran-perf/esda/crand.py#L261)?

**Comment by sjsrey** [comment]
> Is this the relevant [mask](https://github.com/ljwolf/esda/blob/moran-perf/esda/crand.py#L261)?

More debugging:
image

**Comment by ljwolf** [comment]
Yes, the `dtype=boolean` only works for jitted functions, which is why we use it in the jitted mask constructor :/

I'm not sure why this isn't working on your computer, but I'll double-check. It could be:
1. that `z` needs to be 1-dimensional
2. that `mask` needs to be 1-dimensional
3. both.

**Comment by sjsrey** [comment]
Is it possible that there might be files that are not on the remote that I'm missing but you have?

**Comment by ljwolf** [comment]
Nope, it was just that a change broke `Moran_Local` but worked for `Moran_Local_BV`. This has been fixed by keeping `z` flat when it's sent to the conditional randomizer. It appears that `numba` has no problem dealing `z` being either 2d or 1d.

**Comment by ljwolf** [comment]
remaining to do:
- [ ] write the Gi* local crand
- [ ] move joblib underneath `crand.parallell`
- [ ] define a passthrough for `njit` that just returns the function & perftest our new crand engine without numba.

**Comment by darribas** [comment]
Cool! I'd say then maybe remove the old code?

**Comment by ljwolf** [comment]
> Cool! I'd say then maybe remove the old code? 
Sure! would appreciate confirmation others see this, too?

**Comment by ljwolf** [comment]
Remaining to be done:
- [ ] delete the old `crand` codepaths where implemented
- [ ] get the Gi* implementation into crand.py
- [ ] move the local statistical functions into each other module (e.g. move `local_moran` into `moran.py`)
- [ ] tests
- [ ] examples

**Comment by ljwolf** [comment]
Still waiting on the Gi*, @sjsrey, but everything else is OK to go. I think this means we need to start writing tests. I will convert this from "draft" to a "regular" PR now.

**Comment by ljwolf** [comment]
I've added the `Gi` statistics in `getisord.py`, but I'm getting issues I don't yet understand in shaping when running `test_getisord.py`. It appears that when `os.cpu_count()` is larger than the number of observations, you get too many placeholder arrays when `keep_simulations=False`. Not sure if this matters, but I would like to dig a little further into it, and tests may fail. 
```python
# from tests/test_getisord.py
import esda, geopandas
import os
from esda import getisord, moran, crand
from libpysal.weights.distance import DistanceBand
from libpysal.common import pandas
import numpy

points = numpy.asarray([(10, 10), (20, 10), (40, 10), (15, 20), (30, 20), (30, 30)])
w = DistanceBand(points, threshold=15)
y = numpy.array([2, 3, 3.2, 5, 8, 7])

points2 = numpy.row_stack((points, points+50))
w2 = DistanceBand(points2, threshold=15)
y2 = numpy.array([2, 3, 3.2, 5, 8, 7]*2)

lmo = moran.Moran_Local(y, w, permutations=None)
gi = getisord.G_Local(y, w, permutations=None)
lmo2 = moran.Moran_Local(y2, w2, permutations=None)
gi2 = getisord.G_Local(y2, w2, permutations=None)


print(f'This computer has {os.cpu_count()} cores') #is 8 on my Dell 5530
print(f'The first pattern has {points.shape[0]} points') # is (6, 2)
print(f'The second pattern has {points2.shape[0]} points') # is (12,2)
```

**Comment by ljwolf** [comment]
OK, I may have implemented the `Gi` wrong. I was going off of the expression in the LOSH paper. @sjsrey can you take a second look? The implementation is [here](https://github.com/pysal/esda/pull/116/commits/1884487f22a4a8605fd2b59b9291bea57001addc#diff-3f7fbba3eb083a46517151edce6a7752R553).

**Comment by ljwolf** [comment]
It's a scaling issue, I believe. Currently, we implement it that *all* statistics provide a scaling factor to the `crand` engine. For univariates, this is `(n - 1) / (z * z).sum()`, and for bivariate moran, this is `(n - 1) / (z[:, 0] * z[:,0]).sum()`. 

This is not appropriate for all local statistics, especially those in other analytical families (e.g. geary, getis-ord). 

So, we need to offer a method to pass the scaling factor down to the `crand.py` function.

**Comment by ljwolf** [comment]
OK, we will jettison the crand for `G_Local` and focus on finishing the `Moran_Local` family of estimators. The way forward for the G_Local method will be outlined in a separate issue.

**Comment by ljwolf** [comment]
Changes to the getisord crand have been reverted and `keep_simulations` is on by default. @darribas, once the tests are ready, we should be good to go!

**Comment by darribas** [comment]
We'll also need to do some cleaning of the main folder before merging this. Some candidates to (re)move:

- [ ] `test_randomisation.py`
- [ ] `moran-perf.ipynb`
- [ ] `perf-comparison.ipynb`

**Comment by ljwolf** [comment]
The only failures now are the known failures for the chi-squared test in join counts (#123). This should be ready to merge 🥳

**Comment by sjsrey** [comment]
> The only failures now are the known failures for the chi-squared test in join counts (#123). This should be ready to merge partying_face

I think once #124 is merged, this will also pass if rerun.

**Pull request merged**
