### PR TITLE
[WIP] Contributing Smaup test to `esda`

### PR DESCRIPTION
**Pull request by JuancaDuque**
This PR contains code implementing the Smaup test, proposed by:

```
@article{XX,
    author = {Duque, Juan C. AND Laniado, H. AND Polo, A.},
    journal = {PLOS ONE},
    publisher = {Public Library of Science},
    title = {S-maup: Statistical Test to Measure the Sensitivity to the Modifiable Areal Unit Problem},
    year = {2018},
    month = {mm},
    volume = {vv},
    url = {xx},
    pages = {1-25},
    abstract = {This work presents a nonparametric statistical test,  S-maup, to measure the sensitivity of a spatially intensive variable to the effects of the Modifiable Areal Unit Problem (MAUP). To the best of our knowledge,  S-maup is the first statistic of its type and focuses on determining how much the distribution of the variable, at its highest level of spatial disaggregation, will change when it is spatially aggregated. Through a computational experiment, we obtain the basis for the design of the statistical test under the null hypothesis of non-sensitivity to MAUP. We performed an exhaustive simulation study for approaching the empirical distribution of the statistical test, obtaining its critical values, and computing its power and size. The results indicate that, in general, both the statistical size and power improve with increasing sample size. Finally, for illustrative purposes, an empirical application is made using the Mincer equation in South Africa, where starting from 206 municipalities, the  S-maup statistic is used to find the maximum level of spatial aggregation that avoids the negative consequences of the MAUP.},
    number = {nn},
    doi = {xx}
}
```

[[URL]](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0207377)

Opening PR to discuss progress, structure and other details but not to be merged until:

- [ ] Agreed functionality fits in `esda`
- [ ] Structure agreed
- [x] Documentation included
- [x] Tests included

### CODE REVIEW

**Comment by darribas** [comment]
This has come out of a conversation between @JuancaDuque and I. We were debating whether `esda` is the best place. We think so, but Juanca is open. Also, it is currently implemented as a function, I think a class (like say `Moran`) would be better. If these two things are agreed, I'm happy to help out to get this into shape so it can be merged.

**Comment by darribas** [comment]
Tests passing now, any chance this could be merged before meta-release in July?

**Comment by sjsrey** [comment]
I think we can merge, but I wanted to check if there was anything else given the WIP title to the PR?

**Comment by JuancaDuque** [comment]
We forgot to remove the “WP” but everything is there (including the notebooks and tests).
@darribas

**Comment by sjsrey** [comment]
@JuancaDuque @darribas can you update the api.rst docs to reflect this addition? see what @weikang9009 has done for the [fdr addition](https://github.com/pysal/esda/commits/master/doc/api.rst)

**Comment by sjsrey** [comment]
> @JuancaDuque @darribas can you update the api.rst docs to reflect this addition? see what @weikang9009 has done for the [fdr addition](https://github.com/pysal/esda/commits/master/doc/api.rst)

Ignore, as this is now fixed in https://github.com/pysal/esda/pull/62/commits/b7bb49c473ffd7105bb956a19356ec2bfd1282f3

**Pull request merged**
