### PR TITLE
Bug fixes across Lee and swap to survival function for #243

### PR DESCRIPTION
**Pull request by ljwolf**
This addresses a few bugs filed on the Lee statistic, as well as addressing the precision concerns raised in #243 with using `1-stats.norm.cdf()`.

### CODE REVIEW

**Comment by ljwolf** [comment]
Once merged, it would be good to make a bug fix release addressing this, given the lee standardisation issue can have an impact for odd weights specifications.

**Comment by ljwolf** [comment]
test failures for the join counts arise from using the survival function. Not sure where the test failures in the silhouette stats comes from yet.

**Comment by ljwolf** [comment]
So the testing failures in the join counts is, I think, due to the changes upstream in `libpysal` having to do with adjacency lists.

**Comment by ljwolf** [comment]
OK, my understanding is the following. 

With `pysal/libpysal@main`, the following is broken: 

```python
from libpysal.weights.util import lat2W

w = lat2W(3,3)
w.neighbors # this is correct
{0: [3, 1],
 3: [0, 6, 4],
 1: [0, 4, 2],
 4: [1, 3, 7, 5],
 2: [1, 5],
 5: [2, 4, 8],
 6: [3, 7],
 7: [4, 6, 8],
 8: [5, 7]}
w.to_adjlist().head() # this is not
   focal  neighbor  weight
0      0         3     1.0
1      0         4     1.0
2      3         0     1.0
3      3         1     1.0
4      3         2     1.0
```

The issue arises because, [at line 440 of `weights.py`](https://github.com/pysal/libpysal/blob/main/libpysal/weights/weights.py#L440), we use `self.neigbors.keys()`. Since ids are sorted by default **and** dicts now retain their insertion order, the two are not the same: 

```python
w.id_order
[0, 1, 2, 3, 4, 5, 6, 7, 8]
w.neighbors.keys()
dict_keys([0, 3, 1, 4, 2, 5, 6, 7, 8])
```

The ordering that is needed is `w.id_order`, which matches the order in the sparse array we use for the edge tuples. With this libpysal fix, the test failures disappear.

**Review by martinfleis — APPROVED** [review]
Code-wise looks good. If someone close to the actual stats can have a look as well, it'd be good.

**Comment by sjsrey** [comment]
Looks good!

**Review by sjsrey — APPROVED** [review]

**Pull request merged**
