### PR TITLE
BUG: fix join_count contingency table

### PR DESCRIPTION
**Pull request by sjsrey**
Fix for #123

### CODE REVIEW

**Comment by ljwolf** [comment]
What change in scipy changed ths?

**Comment by sjsrey** [comment]
> What change in scipy changed this?

I could not see what in scipy has changed that caused this. 

> What change in scipy changed this? Looking at the [changelog](https://docs.scipy.org/doc/scipy/reference/release.1.5.0.html#scipy-stats-improvements) I don't see a change to `chi2_contingency`?

I couldn't see what changed either, after a lot of digging.

**Comment by sjsrey** [comment]
Flagging as WIP as we should know what caused the breakage before closing.

**Comment by ljwolf** [comment]
I am concerned that this is not a regression introduced in scipy, but rather an issue in (my) code that was not caught at review. 

It's suspicious to me how close the results are to the existing answer when you explicitly compute the bw/bb using the *full* adjacency list and not the de-duplicated list. E.g. compare:
```python
table = numpy.asarray([[20, 4], [4, 20]]) # raw number of joins, undirected
chi2_contingency(table//2) 

table2 = numpy.asarray([[10, 4], [0, 10]])) # using the de-duped version currently in master
```
I think that we need to use the full, not de-duplicated adjacency list and divide the joins by 2 later. If we don't do this, then we may over-count joins in one of the negative autocorrelation types (because the `remove_symmetric` option in `w.to_adjlist()`) can remove either `bw` or `wb`?

**Comment by sjsrey** [comment]
> I am concerned that this is not a regression introduced in scipy, but rather an issue in (my) code that was not caught at review.
> 
> It's suspicious to me how close the results are to the existing answer when you explicitly compute the bw/bb using the _full_ adjacency list and not the de-duplicated list. E.g. compare:
> 
> ```python
> table = numpy.asarray([[20, 4], [4, 20]]) # raw number of joins, undirected
> chi2_contingency(table//2) # much closer to the answer?
> 
> table2 = numpy.asarray([[10, 4], [0, 10]])) # using the de-duped version currently in master
> chi2_contingency(table/2) # what we're changing it to
> ```
> 
> I think that we need to use the full, not de-duplicated adjacency list and divide the joins by 2 later. If we don't do this, then we may over-count joins in one of the negative autocorrelation types (because the `remove_symmetric` option in `w.to_adjlist()` can remove either `bw` or `wb`). I'd definitely like to make sure we're changing the answer correctly here, rather than enshrining a regression...

I think using full is the way to go here. Do you have that change to commit or should I grab it?

**Pull request merged**
