### PR TITLE
modernize CI matrix & deps

### LINKED ISSUE #301: ImportError: rtree library must be installed
Python 3.10-numba {ubuntu, macOS, Windows} [failing](https://github.com/pysal/esda/actions/runs/9847620870/job/27187986681#step:7:879) with:

```
FAILED esda/tests/test_topo.py::TopoTester::test_isolation_options - ImportError: rtree library must be installed to use the prominence measure
FAILED esda/tests/test_topo.py::TopoTester::test_isolation_valid - ImportError: rtree library must be installed to use the prominence measure
```

### LINKED ISSUE #304: list `rtree` in optional requirements?
`rtree` seems to be an optional dependency for `esda` and required to use [`topo.isolation()`](https://github.com/pysal/esda/blob/b8cc7c4c334f08f44a9cb2df46bac0f3faefa6b8/esda/topo.py#L121-L125), but it never made it into:
* [`pyproject.toml`](https://github.com/pysal/esda/blob/b8cc7c4c334f08f44a9cb2df46bac0f3faefa6b8/pyproject.toml#L44)
* [`ci/310-numba.yaml`](https://github.com/pysal/esda/blob/main/ci/310-numba.yaml)
* [`environment.yml`](https://github.com/pysal/esda/blob/main/environment.yml)

Moreover, it is listed as hard dependency in the other CI envs (e.g. [`ci/310.yaml`](https://github.com/pysal/esda/blob/b8cc7c4c334f08f44a9cb2df46bac0f3faefa6b8/ci/310.yaml#L17)), not an optional one.

So I supposed the first Q is: Is `rtree` a hard dependency or not? I supposed not, be we should come to consensus.

xref #301

### LINKED ISSUE #309: CI failure introduced in #306
#306 introduced [a "bug"](https://github.com/pysal/esda/actions/runs/9862439873/job/27233023693?pr=307#step:7:494) - failing 3.8 CI - which can be resolved if we proceed with updated Python version testing -- see [here](https://github.com/pysal/esda/issues/299#issuecomment-2218370883)

### LINKED ISSUE #312: move `geopandas` requirements
Currently, `geopandas` is [list as a `testing` dependency](https://github.com/pysal/esda/blob/a9a4d4f7a1a893cafc6461e25dd4509cc06c7eef/pyproject.toml#L51), but we should probably move it to a new category since it can be imported for optional functionality in [`adbscan.get_cluster_boundary()`](https://github.com/pysal/esda/blob/a9a4d4f7a1a893cafc6461e25dd4509cc06c7eef/esda/adbscan.py#L509)

This will affect #307.

xref #311

### LINKED ISSUE #313: add `plus` dependency section in `pyproject.toml`
Considering[^1][^2], we should add a `plus` dependencies section in `pyproject.toml` including:

* ~~`geopandas`~~ #312 
* `numba`
* `rtree`
* ~~`shapely`~~ #312 
* etc...?

[^1]: #304 
[^2]: #312

### LINKED ISSUE #314: sync requirements & versions
We need to sync requirements (& versions) across the following:

* `pyproject.toml`
* `ci/*`
* `environment.yaml`
* `README` - [*Requirements*](https://github.com/pysal/esda?tab=readme-ov-file#requirements)

The packages and versions in the files vary considerably.

### LINKED ISSUE #315: prune CI testing matrix - only test windows & macOS on latest Python
Currently we are testing against windows & macOS for Python 3.10 (w/ `numba`) and Python 3.11 (w/o `numba`). Since `numba` is available up to Python 3.12 now, we can dispense with those and prune the CI testing matrix. 

xref #310

### LINKED ISSUE #316: update CI env naming conventions
update CI env naming conventions to follow those in [`momepy`](https://github.com/pysal/momepy/tree/main/ci/envs) & [`spopt`](https://github.com/pysal/spopt/tree/main/ci)

* `...-min` -- minimal dependencies -- only hard requirements -- "no optional"
* `...-oldest` -- pinned to oldest supported Python version & packages
* `...-latest` -- no pins (accept Python version) for environment dependencies
* `...-dev` -- fetching bleeding edge versions of dependencies, either from nightly PyPI or directly from GitHub
* other?

***(should also probably do this in [`libpysal`]()...)***

xref #310

### LINKED ISSUE #317: test against both oldest versions & minimal requirements
This current CI schema actually does not test again either oldest versions or minimal requirements. These are 2 separate scenarios and should be treated as such. Probably a single `-oldest` environment with all optional requirements included and a single `-min` environment with no optional requirements included.

xref #316

### LINKED ISSUE #320: Add `folium` and `mapclassify` to testing dependencies
Add `folium` and `mapclassify` to testing dependencies [as per](https://github.com/pysal/esda/actions/runs/9864673024/job/27240080944?pr=318#step:7:1984):

```
FAILED esda/tests/test_moran.py::Moran_Local_Tester::test_Moran_Local_explore
  - ImportError: The 'folium', 'matplotlib' and 'mapclassify' packages are required for 'explore()'.
     You can install them using 'conda install -c conda-forge folium matplotlib mapclassify' or
     'pip install folium matplotlib mapclassify'.
```

xref #318

### LINKED ISSUE #321: remove bleeding edge libpysal install from `testing.yml`
[This block](https://github.com/pysal/esda/blob/a9a4d4f7a1a893cafc6461e25dd4509cc06c7eef/.github/workflows/testing.yml#L70-L73) can be removed since `libpysal` is being installed from GitHub within the CI environments marked `dev`.

https://github.com/pysal/esda/blob/a9a4d4f7a1a893cafc6461e25dd4509cc06c7eef/.github/workflows/testing.yml#L70-L73

### LINKED ISSUE #322: skip test if `rtree` not installed optional
* skip test if `rtree` not installed optional
* xref
   * #318  
   * #304 

https://github.com/pysal/esda/blob/a9a4d4f7a1a893cafc6461e25dd4509cc06c7eef/esda/tests/test_topo.py#L50

https://github.com/pysal/esda/blob/a9a4d4f7a1a893cafc6461e25dd4509cc06c7eef/esda/tests/test_topo.py#L64

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR modernizes the `esda` CI matrix & dependencies.

* resolves #322 
* resolves #321 
* resolves #320 
* ***STILL UNRESOLVED*** #319 ***need to `libpysal` release***
   * https://github.com/pysal/libpysal/issues/748 
   * xref - #311
   * xref - #299
* resolves #317 
* resolves #316 
* resolves #315 
* resolves #314 
* resolves #313 
* resolves #312 
* resolves #309 
* supersedes #307
* resolves #304 
* resolves #301

### CODE REVIEW

**Comment by jGaboardi** [comment]
### Failures


#### [CI (ubuntu-latest, ci/310-numba-oldest.yaml)](https://github.com/pysal/esda/pull/318#logs)

---------------------

* need new release of `libpysal` -- #319 
```
FAILED esda/tests/test_shape.py::test_reflexive_angle_ratio - numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at resolving type of attribute "atan2" of "$192load_global.46".
module 'numpy' has no attribute 'atan2'
During: typing of get attribute at /home/runner/work/esda/esda/esda/shape.py (126)
Enable logging at debug level for details.

File "esda/shape.py", line 126:
def _get_angles(points, n_coords_per_geom):
    <source elided>
        # compute the angle between the segments
        angle = numpy.atan2(a[0] * b[1] - a[1] * b[0], numpy.dot(a, b))
        ^
```

---------------------

#### [CI (ubuntu-latest, ci/311-latest.yaml)](https://github.com/pysal/esda/pull/318#logs)

```
FAILED esda/tests/test_moran.py::Moran_Local_Tester::test_Moran_Local_labels - pyogrio.errors.DataSourceError: None: No such file or directory
```

---------------------

#### [CI (ubuntu-latest, ci/312-dev.yaml)](https://github.com/pysal/esda/pull/318#logs)

```
FAILED esda/tests/test_adbscan.py::ADBSCAN_Tester::test_adbscan - ValueError: assignment destination is read-only
FAILED esda/tests/test_adbscan.py::Remap_lbls_Tester::test_remap_lbls - TypeError: Invalid value '[ 0.  0. nan  7.  7.]' for dtype 'int64'
FAILED esda/tests/test_adbscan.py::Ensemble_Tester::test_ensemble - TypeError: Invalid value '[ 0.  0. nan  7.  7.]' for dtype 'int64'
FAILED esda/tests/test_adbscan.py::Get_Cluster_Boundary_Tester::test_get_cluster_boundary - ValueError: assignment destination is read-only
FAILED esda/tests/test_adbscan.py::i::test_ensemble - TypeError: Invalid value '[ 0.  0. nan  7.  7.]' for dtype 'int64'
FAILED esda/tests/test_map_comparison.py::test_overlay_entropy - ValueError: assignment destination is read-only
FAILED esda/tests/test_map_comparison.py::test_completeness_and_homogeneity - ValueError: assignment destination is read-only
FAILED esda/tests/test_map_comparison.py::test_external_entropy - ValueError: assignment destination is read-only
FAILED esda/tests/test_moran.py::Moran_Local_Tester::test_Moran_Local_explore - ImportError: The 'folium', 'matplotlib' and 'mapclassify' packages are required for 'explore()'. You can install them using 'conda install -c conda-forge folium matplotlib mapclassify' or 'pip install folium matplotlib mapclassify'.
```

---------------------

#### [CI (ubuntu-latest, ci/312-numba-dev.yaml)](https://github.com/pysal/esda/pull/318#logs)
```
FAILED esda/tests/test_adbscan.py::ADBSCAN_Tester::test_adbscan - ValueError: assignment destination is read-only
FAILED esda/tests/test_adbscan.py::Remap_lbls_Tester::test_remap_lbls - TypeError: Invalid value '[ 0.  0. nan  7.  7.]' for dtype 'int64'
FAILED esda/tests/test_adbscan.py::Ensemble_Tester::test_ensemble - TypeError: Invalid value '[ 0.  0. nan  7.  7.]' for dtype 'int64'
FAILED esda/tests/test_adbscan.py::Get_Cluster_Boundary_Tester::test_get_cluster_boundary - ValueError: assignment destination is read-only
FAILED esda/tests/test_adbscan.py::i::test_ensemble - TypeError: Invalid value '[ 0.  0. nan  7.  7.]' for dtype 'int64'
FAILED esda/tests/test_map_comparison.py::test_overlay_entropy - ValueError: assignment destination is read-only
FAILED esda/tests/test_map_comparison.py::test_completeness_and_homogeneity - ValueError: assignment destination is read-only
FAILED esda/tests/test_map_comparison.py::test_external_entropy - ValueError: assignment destination is read-only
FAILED esda/tests/test_moran.py::Moran_Local_Tester::test_Moran_Local_explore - ImportError: The 'folium', 'matplotlib' and 'mapclassify' packages are required for 'explore()'. You can install them using 'conda install -c conda-forge folium matplotlib mapclassify' or 'pip install folium matplotlib mapclassify'.
```

**Comment by jGaboardi** [comment]
Still need to determine decide if we will go with `libpysal==v4.11` or `libpysal==v4.12` for the minimal dependency, but other than that this PR is ready for review.

@sjsrey @knaaptime @martinfleis

**Comment by knaaptime** [comment]
nicely done

**Comment by jGaboardi** [comment]
> nicely done. 13 issues closed in one PR has to be a pysal record...

To be fair, I opened all those (and caused one).

**Review by sjsrey — APPROVED** [review]

**Pull request merged**
