### PR TITLE
geopandas-base in 312-min.yaml

### PR DESCRIPTION
**Pull request by jGaboardi**
geopandas-base in 312-min.yaml -- xref #346

### CODE REVIEW

**Comment by martinfleis** [comment]
Still comes with it. libpysal requires geopandas (not geopandas-base).

**Comment by jGaboardi** [comment]
So:
* If `matplotlib` comes with `geopandas` through `libpysal` as a hard requirement, then it can't really be an optional one here, right?
* If it can be, is it even worth trying to figure out how to tests against not having it? I tried several ways of creating a minimum `esda` environment locally, but each way keeps pulling `matplotlib`.

**Comment by martinfleis** [comment]
We could change the conda-forge recipe to depend on geopandas-base there but I don't think it is worth the hassle.

**Comment by jGaboardi** [comment]
Closing for now. We can look into again as time/energy permit.

**Comment by james-willis** [comment]
geopandas 1.0.1 installed from pip does not have a dependency on matplotlib:

```
➜ pip show geopandas
Name: geopandas
Version: 1.0.1
Summary: Geographic pandas extensions
Home-page:
Author:
Author-email: Kelsey Jordahl <kjordahl@alum.mit.edu>
License: BSD 3-Clause
Location: .../python3.10/site-packages
Requires: numpy, packaging, pandas, pyogrio, pyproj, shapely
Required-by: esda, libpysal
```


This was the entire motivation of my original PR: matplotlib is required by esda but NOT listed in the dependencies package. So when folks run `pip install esda` then have some `from esda.someModule import someFunction` they get a runtime error about matplotlib not being installed. 

If you don't want to accept my original PR, we should at least fix the implicit dependency bug by adding matplotlib to the required dependencies in the pyproject.toml file.

**Pull request closed without merging**
