### PR TITLE
update docs infrastructure

### PR DESCRIPTION
**Pull request by knaaptime**
this pr:
- adds release GHA to release package on githb and pypi via git tag
- adds docs GHA to build docs and publish on gh-pages
- removes unnecessary `docsrc`
- rename esda.yml-->environment.yml and fill out deps
- add missing deps to requirements_docs

### CODE REVIEW

**Review by jGaboardi — COMMENTED** [review]
@knaaptime Should the [`Makefile`](https://github.com/pysal/esda/pull/163/files) be moved to `docs/` (and edited) rather than deleting?

**Review by jGaboardi — APPROVED** [review]

**Comment by jGaboardi** [comment]
@knaaptime Shall we merge?

**Comment by knaaptime** [comment]
i dont have admin rights on esda, but we need to switch the docs to serve from gh-pages branch @sjsrey @ljwolf

**Comment by ljwolf** [comment]
We need to make folks get commit rights across the team.....

**Comment by knaaptime** [comment]
well i'm allowed to commit/merge, but i cant go to the settings and change which branch the docs are served from

**Comment by jGaboardi** [comment]
> well i'm allowed to commit/merge, but i cant go to the settings and change which branch the docs are served from

Same, it's the "top-level" rights we need to have access to the *Settings* tab.

**Comment by sjsrey** [comment]
@knaaptime i changed the branch on gh-pages but we are 404'ng. Does something need to be restarted?

**Comment by knaaptime** [comment]
serve from the root, not the docs folder

**Comment by sjsrey** [comment]
image

**Comment by ljwolf** [comment]
Ah, missed local geary?

**Comment by ljwolf** [comment]
I've added admin rights to devs on this repository.

**Comment by sjsrey** [comment]
> image

It's still 404?

**Comment by jGaboardi** [comment]
It's loading without issue for me.

**Comment by jGaboardi** [comment]
Screen Shot 2021-01-27 at 4 11 36 PM

**Comment by knaaptime** [comment]
i think its a just a timeout thing at the moment. oddly, for me https://pysal.org/esda gives me 404 but https://pysal.org/esda/index.html works

**Comment by jGaboardi** [comment]
> i think its a just a timeout thing at the moment. oddly, for me https://pysal.org/esda gives me 404 but https://pysal.org/esda/index.html works

Both working for me

**Comment by sjsrey** [comment]
> i think its a just a timeout thing at the moment. oddly, for me https://pysal.org/esda gives me 404 but https://pysal.org/esda/index.html works

Same for me.

**Pull request merged**
